### ISSUE TITLE
Build-environment problems

### ISSUE THREAD

**Issue by gerald-b** [thgier/PotatoPresenter#2]
Hello,

i'm trying to build it on my own.
but i got stuck.

Steps:
* Install fresh "linux mint 20.2 Cinnamon"
* apt install git cmake g++
* git clone https://github.com/thgier/PotatoPresenter.git
* cd PotatoPresenter
* mkdir build
* cmake -S . -B ./build/
After that i got an error

> -- The CXX compiler identification is GNU 9.3.0
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at CMakeLists.txt:19 (find_package):
>   By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5" with any of
>   the following names:
> 
>     Qt5Config.cmake
>     qt5-config.cmake
> 
>   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
>   to a directory containing one of the above files.  If "Qt5" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/edv/sources/PotatoPresenter/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/thgier/PotatoPresenter/files/7781905/CMakeOutput.log)

Can i have any hint for getting this software running?

**Comment by sur5r** [comment]
On Debian and derivatives, you'll need to install the following packages for building:
- `qtbase5-dev`
- `libantlr4-runtime-dev`
- `libkf5texteditor-dev`
- `libkf5syntaxhighlighting-dev`

Additionally, I found the following packages to be necessary at runtime:
- `texlive-science`
- `texlive-fonts-extra`

Both lists might be incomplete, I did not try it on a minimal install yet.

**Comment by gerald-b** [comment]
@sur5r thanks a lot.

NOTE: `apt install libqt5svg5-dev qtbase5-dev libantlr4-runtime-dev libkf5texteditor-dev libkf5syntaxhighlighting-dev`

**Comment by thgier** [comment]
Thank you for the list:)
I am planning to put a script for building the appimage in the repository. There will be the up-to-date dependencies.

**Comment by thgier** [comment]
On the master branch is now in build_AppImage a Dockerfile. There are all needed dependencies.

**Comment by thgier** [comment]
There is now a detailed description how to build it from source on the webside: https://potato-presenter.de/contribute.html

**Comment by t3st-account** [comment]
there seem s  to be missing a '&&' in the build section for antrl4:
env CXX=g++-11 **&&** cmake .  -DANTLR4_INSTALL=ON -DWITH_DEMO=False
