### ISSUE TITLE
Paths cannot contain dots

### ISSUE THREAD

**Issue by ahormann** [thgier/PotatoPresenter#5]
If i want to create a new presentation from a template at path '/a/b.c/d' it fails with 
'Failed to find /a/b.json. Genereate a new empty Configuration File'

If i move an existing presentation to '/a/b.c/d' a new json '/a/b.json' is created which stores future changes.

Also 'Genereate' seems to be a typo.

These problems are only mildly annoying but i wanted to report them regardless.

**Comment by thgier** [comment]
Thank you, I fixed this in release 1.0.2.
